#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line

c=0

while [ $c -lt 10 ]
do
  if [ $c == 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( c++ ))
done
